common_library_sources = files(
  'execution_context.cpp',
  'getters/ebml.cpp',
  'getters/helpers.cpp',
  'getters.cpp',
  'guid.cpp',
  'helper.cpp',
  'id3_de_unsynchronization_eager_filter.cpp',
  'inspector.cpp',
  'output_operators.cpp',
  'query.cpp',
  'reader.cpp',
  'type_definition/add.cpp',
  'type_definition/add_tag.cpp',
  'type_definition/alternative.cpp',
  'type_definition/and.cpp',
  'type_definition/apply_cast.cpp',
  'type_definition/apply_enumeration.cpp',
  'type_definition/array.cpp',
  'type_definition/bits_interpretation.cpp',
  'type_definition/cast.cpp',
  'type_definition/data_reference.cpp',
  'type_definition/divide.cpp',
  'type_definition/enumeration.cpp',
  'type_definition/equals.cpp',
  'type_definition/expression.cpp',
  'type_definition/field.cpp',
  'type_definition/field_reference.cpp',
  'type_definition/forward.cpp',
  'type_definition/function_call.cpp',
  'type_definition/helper.cpp',
  'type_definition/length.cpp',
  'type_definition/less_than.cpp',
  'type_definition/modulus.cpp',
  'type_definition/multiply.cpp',
  'type_definition/part.cpp',
  'type_definition/parameter_reference.cpp',
  'type_definition/parameters.cpp',
  'type_definition/select.cpp',
  'type_definition/sequence.cpp',
  'type_definition/subtract.cpp',
  'type_definition/tag.cpp',
  'type_definition/type.cpp',
  'type_definition/type_reference.cpp',
  'type_definition/value.cpp',
  'type_definition/verification.cpp',
  'type_repository.cpp',
)

common_library_sources += configure_file(
  configuration: {
    'TYPE_LIBRARY_PATH': type_library_path
  },
  input: 'type_library_path.h.in',
  output: 'type_library_path.h'
)
