name: Build & Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository with submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: make
    - name: Test
      run: make check
