name: Build & Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository with submodules
      uses: actions/checkout@v4
    - name: Install ninja
      run: pip install ninja
    - name: Install meson
      run: pip install meson
    - name: Setup project build directory
      env:
        CC: gcc-14
        CXX: g++-14
      run: meson setup build
    - name: Compile project
      run: meson compile -C build
    - name: Unit tests
      run: meson test -C build
